# Generated by Django 3.2.10 on 2022-01-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WfmtTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_number', models.CharField(max_length=200)),
                ('sne_id', models.IntegerField()),
                ('scheme_number', models.IntegerField()),
                ('trs', models.CharField(max_length=10)),
                ('estimate', models.CharField(max_length=10)),
            ],
        ),
    ]
